language: cpp
sudo: false
cache: ccache
os: linux
matrix:
  include:
    - name: "Build 32 Bit"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - libc6-dev-i386
            - gcc-6-multilib g++-6-multilib
            - linux-libc-dev:i386
      install:
        - export CC='ccache gcc-6' CXX='ccache g++-6' JOBS=2
      script:
        - ./configure --without-dtrace --without-etw --without-perfctr --without-ssl --without-inspector --without-intl --without-snapshot --dest-cpu x86 --without-bundled-v8
        - make -j2 V=
